Add Alipay, Baidu, Bilibili and Zhihu websites:
jdm-contrib/jdm pull request #1740
Opened 2023-08-01 16:17 UTC by tomac4t

- Add Alipay as medium
- Add Baidu as medium
- Add Bilibili as medium
- Change QQ as medium
- Add notes for QQ
- Update url for QQ (The former is Wechat one, not QQ.)
- Change Wechat as medium
- Add notes for Wechat
- Add Zhihu as easy
- Add Weibo as medium
- Add Elsevier.com as hard

2023-08-03 14:17 UTC, WebSnke requested changes
I added some suggestions to your code.

2023-08-03 14:18 UTC, WebSnke commented
It would be great if you could create separate pull requests in the future.

2023-08-03 14:57 UTC, WebSnke commented on _data/sites.json
> +        "url": "https://service.elsevier.com/app/answers/detail/a_id/30148/supporthub/ecommerce/~/how-do-i-request-deletion-of-my-elsevier.com-account",
> I don't see the support email on that page:(

Yeah, me neither.

2023-08-08 09:59 UTC, tupaschoal commented on _data/sites.json
> +
Needs to be moved after Bigstock to fix alphabetical sorting.

2023-08-08 10:08 UTC, tupaschoal reviewed
Most of the comments are just to standardize the arrows we just changed, but there are a few questions there.

2023-08-08 10:08 UTC, tupaschoal commented on _data/sites.json
> +        "notes": "From the app: Settings → Account and Security → Account Cancel.",
```suggestion
        "notes": "From the app: Settings ⮕ Account and Security ⮕ Account Cancel.",
```

2023-08-08 10:08 UTC, tupaschoal commented on _data/sites.json
> +        "difficulty": "medium",
Why is it medium? I feel like this needs some explanation

2023-08-08 10:08 UTC, tupaschoal commented on _data/sites.json
> +        "difficulty": "medium",
Same comment about being medium here.

2023-08-08 10:08 UTC, tupaschoal commented on _data/sites.json
> +        "notes": "From the app: Avatar → Settings → Account Security → Account Cancellation.",
```suggestion
        "notes": "From the app: Avatar ⮕ Settings ⮕ Account Security ⮕ Account Cancellation.",
```

2023-08-08 10:08 UTC, tupaschoal commented on _data/sites.json
> +        "notes": "From the app: Me → Settings → Account Security → WeChat Security Center → Account Cancellation.",
```suggestion
        "notes": "From the app: Me ⮕ Settings ⮕ Account Security ⮕ WeChat Security Center ⮕ Account Cancellation.",
```

2023-08-09 12:47 UTC, tupaschoal commented on _data/sites.json
> +        "difficulty": "medium",
I see

2023-08-09 12:48 UTC, merged