Add Akinator
jdm-contrib/jdm pull request #1821
Opened 2023-10-09 21:43 UTC by alrjunior

2023-10-10 08:37 UTC, Kefaku requested changes

2023-10-10 08:37 UTC, Kefaku commented on _data/sites.json
> +            "akinator.com"
There are more localized/mobile domains.

```suggestion
            "akinator.com",
            "ar.akinator.com",
            "cn.akinator.com",
            "de.akinator.com",
            "en.akinator.com",
            "es.akinator.com",
            "fr.akinator.com",
            "id.akinator.com",
            "il.akinator.com",
            "it.akinator.com",
            "jp.akinator.com",
            "kr.akinator.com",
            "nl.akinator.com",
            "pl.akinator.com",
            "pt.akinator.com",
            "ru.akinator.com",
            "tr.akinator.com",
            "akinator.mobi",
            "ar.akinator.mobi",
            "cn.akinator.mobi",
            "de.akinator.mobi",
            "en.akinator.mobi",
            "es.akinator.mobi",
            "fr.akinator.mobi",
            "id.akinator.mobi",
            "il.akinator.mobi",
            "it.akinator.mobi",
            "jp.akinator.mobi",
            "kr.akinator.mobi",
            "nl.akinator.mobi",
            "pl.akinator.mobi",
            "pt.akinator.mobi",
            "ru.akinator.mobi",
            "tr.akinator.mobi"
```

2023-10-10 21:11 UTC, tupaschoal commented on _data/sites.json
> +        "notes": "At the app ⮕ Click in settings (gear icon) ⮕ Account settings ⮕ Delete account (at the bottom of the screen).",
```suggestion
        "notes": "At the app, click on settings (gear icon) ⮕ Account settings ⮕ Delete account (at the bottom of the screen).",
```

2023-10-10 21:11 UTC, tupaschoal commented on _data/sites.json
> +        "notes_pt_br": "No aplicativo ⮕ Clique em configurações (ícone da engrenagem) ⮕ Configurações de conta ⮕ Excluir conta (no fim da tela).",
```suggestion
        "notes_pt_br": "No aplicativo, clique em configurações (ícone da engrenagem) ⮕ Configurações de conta ⮕ Excluir conta (no fim da tela).",
```

2023-10-11 10:25 UTC, tupaschoal approved these changes

2023-10-11 10:25 UTC, merged

2023-10-11 10:25 UTC, tupaschoal commented
Thanks for your contribution!