Added Pillpack
jdm-contrib/jdm pull request #1852
Opened 2023-10-30 12:31 UTC by Possibly6757

2023-10-30 20:09 UTC, Kefaku requested changes

2023-10-30 20:09 UTC, Kefaku commented on _data/sites.json
> +            "https://www.pillpack.com/"
There are more domains:

```suggestion
            "pillpack.com",
            "app.pillpack.com",
            "folks.pillpack.com",
            "my.pillpack.com"
```

2023-10-30 20:35 UTC, tupaschoal commented on _data/sites.json
> +        "name": "Pillpack",
```suggestion

    {
        "name": "Pillpack",
```

2023-10-30 20:35 UTC, tupaschoal commented on _data/sites.json
>      {
```suggestion
    },

    {
```

2023-10-31 10:45 UTC, merged

2023-10-31 10:45 UTC, tupaschoal commented
Thanks for your contribution!