Add Character.Ai as Easy
jdm-contrib/jdm pull request #1885
Opened 2023-11-14 20:42 UTC by GuiReboucas

# Character.ai (beta.character.ai)
---
https://beta.character.ai/settings/

Scroll to the bottom of the settings page on your profile and click ”Remove Account“, then insert your username and choose whether you want to export your data while deleting it or not.

2023-11-15 01:48 UTC, tupaschoal reviewed
Can you move the entry so it is sorted on the JSON, please?

2023-11-15 01:48 UTC, tupaschoal commented on _data/sites.json
> +    {
```suggestion
    },

    {
```

2023-11-15 19:49 UTC, Kefaku requested changes
There are 2 more domains in use:

2023-11-15 19:49 UTC, Kefaku commented on _data/sites.json
> +		"beta.character.ai"
```suggestion
		"character.ai",
		"book.character.ai",
		"beta.character.ai"
```

2023-11-16 02:33 UTC, tupaschoal reviewed
The entry still needs to be moved to the right order in the JSON file.

2023-11-16 05:34 UTC, GuiReboucas commented
> The entry still needs to be moved to the right order in the JSON file.

Oh damn my bad

2023-11-19 10:26 UTC, tupaschoal approved these changes

2023-11-19 10:27 UTC, merged

2023-11-19 10:27 UTC, tupaschoal commented
Thanks for your contribution!