Add Computeruniverse, iLoveIMG, iLovePDF, Flathub & Reverso
jdm-contrib/jdm pull request #2005
Opened 2024-03-09 14:43 UTC by JustMarkov

Add Computeruniverse (as hard), iLoveIMG (as hard), iLovePDF (as hard), Flathub (as easy) & Reverso (as hard)

Notes languages: en & ru

P.S.: I hope there's no syntax errors this time.
P.P.S.: Separated iLoveIMG and iLovePDF 'cause of different domains and contact forms. Not sure if the accounts are shared, tho.

2024-03-09 20:37 UTC, Kefaku requested changes
There are some missing domains.

2024-03-09 20:37 UTC, Kefaku commented on _data/sites.json
> +            "ilovepdf.com"
```suggestion
            "ilovepdf.com",
            "developer.ilovepdf.com"
```

2024-03-09 20:37 UTC, Kefaku commented on _data/sites.json
> +            "iloveimg.com"
```suggestion
            "iloveimg.com",
            "developer.iloveimg.com"
```

2024-03-09 20:37 UTC, Kefaku commented on _data/sites.json
> +            "reverso.net",
```suggestion
            "reverso.net",
            "coniugazione.reverso.net",
            "conjugacao.reverso.net",
            "conjugador.reverso.net",
            "conjugator.reverso.net",
            "conjugueur.reverso.net",
```

2024-03-09 20:37 UTC, Kefaku commented on _data/sites.json
> +            "dictionary.reverso.net",
```suggestion
            "diccionario.reverso.net",
            "dicionario.reverso.net",
            "dictionary.reverso.net",
            "dictionnaire.reverso.net",
            "dizionario.reverso.net",
```

2024-03-09 20:37 UTC, Kefaku commented on _data/sites.json
> +            "context.reverso.net",
```suggestion
            "context.reverso.net",
            "corporate-translation.reverso.com",
```

2024-03-09 20:37 UTC, Kefaku commented on _data/sites.json
> +            "grammar.reverso.net"
```suggestion
            "grammar.reverso.net",
            "konjugator.reverso.net",
            "woerterbuch.reverso.net"
```

2024-03-10 09:09 UTC, JustMarkov commented
@Kefaku thanks for your suggestions! I added all of your commits.

2024-03-10 09:52 UTC, tupaschoal approved these changes

2024-03-10 09:52 UTC, merged

2024-03-10 09:52 UTC, tupaschoal commented
Thanks for all these new entries!