Add back4app as hard
jdm-contrib/jdm pull request #2254
Opened 2024-09-09 17:48 UTC by AverageHelper

Added [back4app](https://www.back4app.com/) account deletion instructions, and a link to the relevant Help article.

2024-09-10 17:41 UTC, Kefaku requested changes

2024-09-10 17:59 UTC, AverageHelper commented on _data/sites.json
> +            "www.back4app.com"
Thanks!

2024-09-11 23:35 UTC, tupaschoal approved these changes

2024-09-11 23:35 UTC, merged

2024-09-11 23:35 UTC, tupaschoal commented
Thanks for your contribution!