Add more websites
jdm-contrib/jdm pull request #2309
Opened 2024-10-29 18:04 UTC by flexagoon

2024-10-29 20:03 UTC, Kefaku commented on _data/sites.json
> +            "chemaxon.com"
```suggestion
            "chemaxon.com",
            "docs.chemaxon.com"
```

2024-10-29 20:11 UTC, Kefaku requested changes
There is another domain

2024-10-30 10:49 UTC, tupaschoal commented on _data/sites.json
> +        "difficulty": "medium",
```suggestion
        "difficulty": "hard",
```
Moving to hard since it needs a deletion request, which likely is human-aided.

2024-10-30 10:58 UTC, tupaschoal approved these changes

2024-10-30 11:00 UTC, merged

2024-10-30 11:00 UTC, tupaschoal commented
Thanks for your contribution!