Add ITV.com
jdm-contrib/jdm pull request #955
Opened 2021-09-20 11:58 UTC by kymckay

Another simple entry

2021-09-21 02:46 UTC, tupaschoal reviewed
The link doesn't seem to be a direct deletion one. Does the page have a very hard to miss delete button or similar?

Otherwise it might be useful to introduce some notes.

2021-09-24 17:14 UTC, Spectroxx requested changes
Notes should be required on all pull requests for sites.json
Specifically when adding sites.

2021-09-24 17:14 UTC, Spectroxx commented on _data/sites.json
> +        "url": "https://www.itv.com/hub/user/profile",
Add notes so the directive is more concise with the end-user.

2021-09-24 18:45 UTC, kymckay commented
I disagree since default notes were added. However, for this entry I will add a short note.

2021-09-24 19:29 UTC, tupaschoal approved these changes

2021-09-24 19:29 UTC, merged

2021-09-24 19:29 UTC, tupaschoal commented
Thanks for your contribution!