Updated 8, added 2 sites
jdm-contrib/jdm pull request #994
Opened 2021-11-18 06:06 UTC by SvicidalBug

Closes #990, #991
- Updated Barnes & Noble's URL.
   - I forgot to change the link when I last updated it's notes. 
- Updated Font Awesome's URL and notes. Removed it's email, as emailing is no longer necessary.
- Updated Change.org's URL, difficulty, notes, and added an email address.
   - Change.org does have a web form to submit deletion requests through, but it is currently not working properly. I contacted their support and they confirmed they do also accept account deletion requests sent to help@change.org.
- Updated Channel 4's URL, notes, and removed notes translation.
- Updated NoIP's URL, notes, and removed notes translations.
- Updated Bitly's URL, notes, and removed notes translations.
- Updated Airbnb's URL, difficulty, notes, and notes translations.
- Updated Aliexpress's URL, notes, and removed notes translations.
   - The previous instructions were describing how to _deactivate_ an account.

Added two sites with data provided by @Nachtalb in #990, #991 :
LogMeIn / Hamachi
9anime

#992 doesn't contain a `url`, so I left it out of this PR for now.

2021-11-23 13:01 UTC, Spectroxx commented
Before merging, would it be possible to find people to re-translate the descriptions?

2021-11-23 19:54 UTC, tupaschoal requested changes
It's a bit difficult to get active translators to maintain the descriptions, so we recommend just deleting the translations whenever the notes change significantly

2021-11-23 21:59 UTC, SvicidalBug commented
> It's a bit difficult to get active translators to maintain the descriptions, so we recommend just deleting the translations whenever the notes change significantly

I added back the notes for Avast, Bitly, and NoIP as they do still make sense, but could definitely be improved. The rest of the notes have changed significantly and I feel it's best to leave out their translations.

2021-11-24 09:48 UTC, tupaschoal approved these changes
Thanks for the very thorough PR description and such an extensive update :)

2021-11-24 09:48 UTC, merged